### ISSUE TITLE
🧑‍💻 documentation 

### ISSUE THREAD

**Issue by i99dev** [sspaeti/mdbook-sspaeti#1]
Hey Simon Späti,

 I'm new to Rust and would like to use your script. Can you please guide me on how to use it?
 
 thanks, advance

**Comment by sspaeti** [comment]
It's only useful for my website, as I ended up only replacing wikilinks `[[]]` linking automatically to my second brain. Which might not be useful to anyone else. 

## Small How-to
If I have a little time, I might update more, but for now, I can give a quick note about how I set it up:

1. I installed it through `cargo install mdbook-sspaeti` (I guess, maybe this part I did manually)
2. I added this config to my `book.toml`:
```toml
[preprocessor.sspaeti]
command = "mdbook-sspaeti"
brain-base-url = "https://ssp.sh/brain" #link to website you want `[[my-link]]` point to. e.g. `https://ssp.sh/brain/my-link`
```

The preprocessor will automatically check on each run, if the links are valid and or not like this (might be a bit verbose each time..)
```
...
mdbook-sspaeti- check_link: The URL returned an ERROR: 404 Not Found, http://ssp.sh/brain/streaming-vs-batch-in-orchestration
mdbook-sspaeti- check_link: The URL is valid: http://ssp.sh/brain/semantic-layer
...
```

Hope that helps for now.

PS: Thanks for the hint, I quickly updated the [readme](https://github.com/sspaeti/mdbook-sspaeti/) as well.
